version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
